version: '3.7'

services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    volumes:
      - jenkins_volume:/var/jenkins_home
    ports:
      - 8080:8080

volumes:
  jenkins_volume:
    driver: local 
